version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  
  mosca:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "1883:1883"   
    depends_on:
      - redis   
      